name: Disparo Automatico Agenda
on:
  schedule:
    - cron: '*/5 * * * *' # O GitHub vai disparar a cada 5 minutos
  workflow_dispatch:      # Permite disparar manualmente para testar

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar API de Producao
        run: |
         curl -X GET "https://agendamarketing-eight.vercel.app/api/cron?key=${{ secrets.CRON_SECRET }}"
