name: Despertador de Agendamento
on:
  schedule:
    - cron: '*/5 * * * *' # Roda a cada 5 minutos

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar API de Disparo
        run: curl -X GET "https://agendamarketing-eight.vercel.app/api/cron"
